### ISSUE TITLE
Build broken on nightly

### ISSUE THREAD

**Issue by caelunshun** [yoanlcq/vek#67]
Compiling with latest nightly causes the following errors:

```
error[E0075]: SIMD vector length must be a power of two
    --> /Users/caelum/.cargo/registry/src/github.com-1ecc6299db9ec823/vek-0.12.0/src/vec.rs:2803:13
     |
2803 |               pub struct Vec3<T> { pub x:T, pub y:T, pub z:T }
     |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
...
3195 | /     vec_impl_all_vecs!{
3196 | |         simd
3197 | |         #[repr(simd)]
3198 | |     }
     | |_____- in this macro invocation
     |
     = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0075]: SIMD vector length must be a power of two
    --> /Users/caelum/.cargo/registry/src/github.com-1ecc6299db9ec823/vek-0.12.0/src/vec.rs:3022:13
     |
3022 |               pub struct Extent3<T> { pub w:T, pub h:T, pub d:T }
     |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
...
3195 | /     vec_impl_all_vecs!{
3196 | |         simd
3197 | |         #[repr(simd)]
3198 | |     }
     | |_____- in this macro invocation
     |
     = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0075]: SIMD vector length must be a power of two
    --> /Users/caelum/.cargo/registry/src/github.com-1ecc6299db9ec823/vek-0.12.0/src/vec.rs:3112:13
     |
3112 |               pub struct Rgb<T> { pub r:T, pub g:T, pub b:T }
     |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
...
3195 | /     vec_impl_all_vecs!{
3196 | |         simd
3197 | |         #[repr(simd)]
3198 | |     }
     | |_____- in this macro invocation
     |
     = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error: aborting due to 3 previous errors
```

**Comment by caelunshun** [comment]
Seems to be caused by https://github.com/rust-lang/rust/pull/80652

**Comment by yoanlcq** [comment]
Hi,
It looks like you aren't compiling with the latest 0.14 version, which has a fix for that. The related issue was #66 .

Please try that and let me know how it goes :)

**Comment by caelunshun** [comment]
> Hi,
> It looks like you aren't compiling with the latest 0.14 version of vek, which has a fix for that. The related issue was #66 .
> 
> Please try that and let me know how it goes :)

Ah, thanks. I had updated but still had `vek` 0.12 in my dependency tree. Removing that fixed the issue. Thanks!
